version: '3'

services:
  web:
    build: ./www
    ports:
      - "80:80"
    env_file:
     - .env
    volumes:
      - ./www:/var/www
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: